# Generated by Django 5.0 on 2023-12-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_connection', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
