# Generated by Django 5.0 on 2023-12-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
